### ISSUE TITLE
header menu health and beauty

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Dezymart-Store-ReDesign#10]
**The actual result:** 
![image](https://user-images.githubusercontent.com/102131636/160081159-d1a51962-55d3-4467-a30d-f66aad445067.png)
When we hover over the health and beauty navigation last to the header then images are missing and it also the same navigation used in  the header.

**The expected result:**
Same name navigation should not be used in the header

**Comment by devSuneel** [comment]
resolved

https://b1z09xsd27boxuhp-56773443766.shopifypreview.com

**Comment by sudhanshu0603** [comment]
ok
