### ISSUE TITLE
Collection page filter and wishlist issue

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Dezymart-Store-ReDesign#12]
**Steps:**
1: https://064npycdlbpdj9lv-56773443766.shopifypreview.com/collections/health-and-beauty
2: When we click on the filters then  select any option on it EX: alphabet a-z.

**The actual result:**
1: Then the wishlist icon on the header will disappear on using the filter.
![image](https://user-images.githubusercontent.com/102131636/160083424-861882cc-700a-41c2-90ae-f87674281087.png)

**The expected result:**
When we use the filter in every collection page, then wishlist should be visible in the product page.
![image](https://user-images.githubusercontent.com/102131636/160083323-0c89a6c9-b5fd-4878-afd9-9910cca33148.png)

**Comment by devSuneel** [comment]
resolved

https://b1z09xsd27boxuhp-56773443766.shopifypreview.com

**Comment by sudhanshu0603** [comment]
ok
