### ISSUE TITLE
home page banner 

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Dezymart-Store-ReDesign#13]
**The actual result:** 
The banners of the main home page are not auto- rotate.
![image](https://user-images.githubusercontent.com/102131636/160084521-62b05e71-a770-4d8d-84bd-18c996b6d900.png)

**The expected result:**
The banners have to be auto- rotate, it will be much better.

**Comment by devSuneel** [comment]
resolved

https://b1z09xsd27boxuhp-56773443766.shopifypreview.com

**Comment by sudhanshu0603** [comment]
ok
