### ISSUE TITLE
login page

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Dezymart-Store-ReDesign#16]
**Steps:**
The url: https://064npycdlbpdj9lv-56773443766.shopifypreview.com/account/login

**The actual result:**
The validations are missing on the login page, without filling the data when we click on the SIGN IN button then form is submitting.

**The expected result:**
The validation should be used in the login form.

**Comment by devSuneel** [comment]
resolved 

https://b1z09xsd27boxuhp-56773443766.shopifypreview.com
