### ISSUE TITLE
Reset your password page

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Dezymart-Store-ReDesign#17]
**Steps:**
1: when we click on the login icon and click on the forgot password.
**The actual result:**
Without filling the email in forgot input field then form is submit.
![image](https://user-images.githubusercontent.com/102131636/160091199-4c9afb11-470b-4d00-91a0-f6f235abd0a0.png)

**The expected result:**
1: The disabled symbol have to come when we hover over the submit button on forgot password, it will be much better.

**Comment by devSuneel** [comment]
resolved

https://b1z09xsd27boxuhp-56773443766.shopifypreview.com
