### ISSUE TITLE
create account form

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Dezymart-Store-ReDesign#18]
**Steps:** 
1: The url: https://064npycdlbpdj9lv-56773443766.shopifypreview.com/account/register
**The actual result:**
The validations are missing, without filling the input when we click on the submit button then form is submitting.
![image](https://user-images.githubusercontent.com/102131636/160092122-44eb219a-c252-4c10-9516-bd0c0157a729.png)

**The expected result:**
1: The disabled symbol have to come when we hover over the submit button and validation should be used properly.
--------------------------------------------------------------------------------------------------------------------------------------

**RETESTING:**
1: The last name is having the validation, last can be blank but it must have validation as we have used in first name. 
![image](https://user-images.githubusercontent.com/102131636/160370287-8c7801da-7c0d-4771-92af-8a7c946ba414.png)
Must show error message for invalid inputs.

------------------------------------------------------------------------------------------------------------------------------------------
**Again retesting:**
**Actual result:** 
1: The error message for the last name is not correct, 
![image](https://user-images.githubusercontent.com/102131636/160831319-3f62b5a7-09e1-4cd4-a473-8fec9d38f940.png)
**Expected result:**
The error have to be same given for the first name.

**Comment by devSuneel** [comment]
resolved
https://b1z09xsd27boxuhp-56773443766.shopifypreview.com

**Comment by devSuneel** [comment]
resolved

**Comment by devSuneel** [comment]
resloved

**Comment by devSuneel** [comment]
resolved

**Comment by sudhanshu0603** [comment]
ok ,resolved
