### ISSUE TITLE
home page( product wishlist icon )

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Dezymart-Store-ReDesign#19]
**The actual result:**
1: When we click on the wishlist icon on the product on the home page, then it is opening the product page.
https://www.awesomescreenshot.com/video/8062619?key=0bce9a466c8d8b1e14b367e1c0a43356

**The expected result:**
When we click on the wishlist icon on the product on the home page then, it must show the wishlist page.

**Comment by devSuneel** [comment]
resoleved

https://b1z09xsd27boxuhp-56773443766.shopifypreview.com

**Comment by sudhanshu0603** [comment]
ok
