### ISSUE TITLE
The left side filter on collection.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Dezymart-Store-ReDesign#20]
**The actual result:**
![image](https://user-images.githubusercontent.com/102131636/160098297-71bd53fa-4ea6-4187-a7e4-0a9755765f3e.png)
The Product type is not having the spacing on the left side filter.

**The expected result:**
There must be some space between the product type filter.

**Comment by devSuneel** [comment]
there is already one letter space

**Comment by sudhanshu0603** [comment]
ok
