### ISSUE TITLE
about us ( footer)  READ More.. link in the footer.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Dezymart-Store-ReDesign#21]
**Steps:**
1: When we click on the read more link in the footer about us.
![image](https://user-images.githubusercontent.com/102131636/160099722-dcb75594-7aa3-4711-8743-892306a8b818.png)

**The actual result:**
When we click on the Read more link then page related to it is having much wide space.
![image](https://user-images.githubusercontent.com/102131636/160100224-06fb5d94-30d7-4701-8e42-21d3b07f764b.png)

**The expected result:**
The page related to it, should not have much empty space.
--------------------------------------------------------------------------------------------------------------------------------------------

**RETESTING :**

Remove the line coming below the read more link.
![image](https://user-images.githubusercontent.com/102131636/160368657-c97da4d3-f63f-4993-befa-f01672d19ef3.png)

**Comment by ui-ravishukla** [comment]
@sudhanshu0603 this is not issue. we have set a height here so space is coming. if the height is not given then the header and footer will stick.
