### ISSUE TITLE
Footer (Policies)

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Dezymart-Store-ReDesign#22]
**Steps:**
1: 
![image](https://user-images.githubusercontent.com/102131636/160101499-b0e59749-7718-4d58-a8ac-67bfe9954e68.png)
2: When we click on the Billing terms and conditions
**The actual result:**
1: When we click on the policies Billing terms and conditions then blank page is coming, the content is missing.
The url: https://064npycdlbpdj9lv-56773443766.shopifypreview.com/pages/billing-terms-conditions
![image](https://user-images.githubusercontent.com/102131636/160101886-b50d06a7-2418-4e29-9c5e-4c4d57e3de4e.png)

**The expected result:**
The content is missing on the page.

--------------------------------------------------------------------------------------------------------------------------------------------
Restesting:
1: **Actual result:** 
The much extra spacing is coming below the content of the billing terms and conditions.
![image](https://user-images.githubusercontent.com/102131636/161731037-70134e11-84fe-4a53-b3d5-5ef6fe6338d8.png)

**Expected result:**
If we reduce the spacing then it will be much better.

**Comment by ui-ravishukla** [comment]
Because there is no content here

**Comment by sudhanshu0603** [comment]
ok dont closed the issue, once we get the content we will close the issue mentioned.

**Comment by ui-ravishukla** [comment]
so I have remove label.

**Comment by devSuneel** [comment]
we do not have the content for the page if client will provide then I will add

**Comment by sudhanshu0603** [comment]
@devSuneel , once we get the content we will closed this until then , it is opened, 
CC: @Shweta-PC

**Comment by sudhanshu0603** [comment]
ok ,resolved
