### ISSUE TITLE
The titles on the policies are missing.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Dezymart-Store-ReDesign#23]
**Steps:**
1:  
![image](https://user-images.githubusercontent.com/102131636/160102382-3ceabb30-9375-431f-9ff2-c9d74d14e661.png)
![image](https://user-images.githubusercontent.com/102131636/160105109-f951f3d0-ec99-40cf-87a3-18b360bd5ef4.png)

**The actual result:**
The video url: https://www.awesomescreenshot.com/video/8063303?key=af3e6ee6480bc7b9318c0741f6789d0c
The titles are missing on all the pages of the policies.

**The expected result:**
1: When we open the pages of the policies then titles have to be added on the all policy pages.
2: Much extra spacing are coming on the pages with its content.
---------------------------------------------------------------------------------------------------------------------------------------
**RETESTING :**
1: The billing terms and condition content is missing,
The preview link : https://8jul4942fz5ea8w7-56773443766.shopifypreview.com/pages/billing-terms-conditions
2: All the titles have to come on the middle of the page for all the policies pages it will be much better.

The issue video : https://www.awesomescreenshot.com/video/8096609?key=bc7db1fab8b50fe2adaf4b0ff07390b1

**Comment by devSuneel** [comment]
resolved

https://064npycdlbpdj9lv-56773443766.shopifypreview.com

**Comment by devSuneel** [comment]
we do not have the content for billing terms and conditions

**Comment by sudhanshu0603** [comment]
ok resolved.
