### ISSUE TITLE
Contact us form in footer

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Dezymart-Store-ReDesign#24]
**Steps:** 
1: Click on the contact ous links in footer.

the url : https://064npycdlbpdj9lv-56773443766.shopifypreview.com/pages/contact-us

**The actual result:**
The video link: https://www.awesomescreenshot.com/video/8063385?key=17a2fcb3dd18502fc57e0f33193a3bdb

without filling the input when we click on the submit button then form should not submit. and validation are missing for  name input field.
**The expected result:**
Without filling the input field, when we click on the submit button then form should not be submitted, the disabled symbol have to come, 
Validation for all input field have to be proper.

**RETESTING :**

**Actual result:** 

When we type the number and alphabet then the name input field have to show the error messages, but it is not showing.
The issue video attached: https://www.awesomescreenshot.com/video/8096439?key=578e61d373fb75d182deff944c4bda20

The email input field is not having the validation.

**Expected result:**
1: Name should accepts only alphabet and shows error message if input field data is not given correct.
2: Email must start with letter then number can be accepts .
These are some of the pattern which can be valid for email are : 
  karan@gmail.com
  karan23@gmail.com
  
  Invalid inputs are : 
  34@gmail.com
  @gmail.com
  34aba@gmail.com

**Comment by devSuneel** [comment]
resolved


https://064npycdlbpdj9lv-56773443766.shopifypreview.com

**Comment by devSuneel** [comment]
@sudhanshu0603 name issue has been resolved or email can be start with number this is not an issue
