### ISSUE TITLE
Newsletter.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Dezymart-Store-ReDesign#25]
**The actual result:** 
the newsletter is missing.
**The expected result:** 
The newsletter have to be added.

**Comment by ui-ravishukla** [comment]
Client had newsletter removed

**Comment by sudhanshu0603** [comment]
ok @ui-ravishukla

**Comment by Shweta-PC** [comment]
It is not required a sper clinet.
