### ISSUE TITLE
Collection page price font size.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Dezymart-Store-ReDesign#27]
The url: https://064npycdlbpdj9lv-56773443766.shopifypreview.com/collections/kids

**The actual result:** 
The font of the price is coming  up and down not aligned properly.
![image](https://user-images.githubusercontent.com/102131636/160113999-65eefceb-6786-4eb4-932f-c51c00b45896.png)

**The expected result:**
The font of the price has to be aligned properly.

**Comment by ui-ravishukla** [comment]
Font family is like that. So This is not issue.

**Comment by sudhanshu0603** [comment]
ok
@ui-ravishukla
