### ISSUE TITLE
Produc page the addtocart /  buy it now / wishlist buttons.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Dezymart-Store-ReDesign#28]
Steps: 
1: The url of product page: https://064npycdlbpdj9lv-56773443766.shopifypreview.com/products/printed-ruffle-hem-cutout-one-piece-swimsuit?variant=41241531220150

**The actual result:**
1: When we open the product page, then addtocart/ buy it now button is coming of unequal size.
![image](https://user-images.githubusercontent.com/102131636/160115886-2613149c-5186-445e-8428-1432075a9d59.png)

2: The wishlist icon is missing.
![image](https://user-images.githubusercontent.com/102131636/160115811-72a9dc7e-9cb1-4db5-8770-384f5f0871d7.png)

3: The learn more link is having much space.
![image](https://user-images.githubusercontent.com/102131636/160115750-fd5847f4-6435-4b07-b15e-6c8c6d944bb7.png)

**The expected result:**
1: The wishlist button have to be added in the product page.
2: The size of the buttons have to be of equal size.
3:  The learn more links can be used below the text.
![image](https://user-images.githubusercontent.com/102131636/160116184-e6691461-734c-44f5-a431-90cd2c522cae.png)

**Comment by ui-ravishukla** [comment]
![image](https://user-images.githubusercontent.com/102217972/160164852-9ff78d49-6870-4ac6-8f8b-149a86c9ec09.png)

Its coming. pls check in strong net speed.

**Comment by sudhanshu0603** [comment]
@ui-ravishukla , Learn more link what we have to do ???
please leave a comment.
