### ISSUE TITLE
price filter in collection 

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Dezymart-Store-ReDesign#29]
**Steps:**
1: The url: https://064npycdlbpdj9lv-56773443766.shopifypreview.com/collections/haircare

**The actual result:** 
1: When we hover over the price filter then by default  cursor is coming.
https://www.awesomescreenshot.com/video/8064964?key=d640c0727bb9061ef48a3f3e7d50cd1b

**The expected result:** 
When we hover over the pricing filter then hand cursor have to come, it will be much  better.

**Comment by ui-ravishukla** [comment]
Fixed
