### ISSUE TITLE
price filter in collection page, ( wishlist disappears)

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Dezymart-Store-ReDesign#30]
**Steps:**
1: The url :https://064npycdlbpdj9lv-56773443766.shopifypreview.com/collections/haircare?filter.v.price.lte=41
2: When we change the price slider then the wishlist is disappearing from the product in collection page,

**The actual result:**
The video: https://www.awesomescreenshot.com/video/8065129?key=b61a9e9f502c85b9bcff59fd27733e13
When we slide the pricing filter then  wishlist icon will disappear.

**The expected result:**
When we change the pricing then the wishlist must be visible properly.

**Comment by devSuneel** [comment]
resolved
https://064npycdlbpdj9lv-56773443766.shopifypreview.com
