### ISSUE TITLE
The tagline of the section BEST SELLERS in home page, are not correct.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Dezymart-Store-ReDesign#32]
The actual result: 
![image](https://user-images.githubusercontent.com/102131636/160123069-ebb17883-bfb6-4922-978f-4979d221370a.png)
The title Men's best and Women both are pattern of naming is different.

The expected result: 
1: The tagline of both have to related to each other.

**Comment by devSuneel** [comment]
resolved
https://064npycdlbpdj9lv-56773443766.shopifypreview.com

**Comment by sudhanshu0603** [comment]
@Shweta-PC , it is resolved
