### ISSUE TITLE
capcha page 

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Dezymart-Store-ReDesign#33]
The actual result: 
![image](https://user-images.githubusercontent.com/102131636/160124449-eb075bba-dfff-447d-95e9-354c0e1e7b1f.png)
When we hover over the submit button on capcha page then hand cursor is not coming.

The expected result: 
The hand cursor have to come when we hover over all the capcha pages.

**Comment by ui-ravishukla** [comment]
Cursor is coming after hovering over button. And Hand cursor will come only on the button.
