### ISSUE TITLE
 Same Thumbnails images in product page are repeated in some of the products.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Dezymart-Store-ReDesign#34]
**Steps:** 
1: The product page: https://064npycdlbpdj9lv-56773443766.shopifypreview.com/products/grey-camouflage-546585253
2: Some of the same thumbnails images are used multiples times for the product.

**The actual result:**
1: 
![image](https://user-images.githubusercontent.com/102131636/160126459-f2059dcb-d2ae-49a9-a091-e3ddf473fb7d.png)
The video : https://www.awesomescreenshot.com/video/8065966?key=8674a2aff5c38a97bd754b8afe352b7b

**The expected result:** 
Same thumbnails images should not be used.

**Comment by sudhanshu0603** [comment]
pls, review it again , it is not resolved. @Shweta-PC .  @devSuneel .

**Comment by devSuneel** [comment]
coming from the product so this is not an issue we can not remove it from each product

**Comment by sudhanshu0603** [comment]
ok, resolved
