### ISSUE TITLE
The return and refund policy.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Dezymart-Store-ReDesign#35]
**Steps:** 
1: When click on the returns and refund policy in footer .

**Actual result:**
When we click on the returns and refund policy link on the footer then url is coming of only returns policy, 
![image](https://user-images.githubusercontent.com/102131636/160356312-b829f29d-00be-4a33-baaf-3b5ecddd2733.png)

**Expected result:**
The url have to be returns and refund policy, as per the page related to it.

**Comment by devSuneel** [comment]
https://dezymart.com/pages/returns-and-refund-policy

**Comment by sudhanshu0603** [comment]
ok, resolved.
