### ISSUE TITLE
Wishlist page after succesfull login

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Dezymart-Store-ReDesign#36]
**Steps:** 
1: email : karan@gmail.com
    password: Karan@12
     Login succesfull , then click on the wishlist icon on the product on homepage.
     
 **Actual result:**    
 1: The removeall button and addall to cart links have some background color  it will be much better.
 2: The images is coming big so vertical scrolling is coming for 1st row we can avoid the vertical  scrolling.
 
![image](https://user-images.githubusercontent.com/102131636/160383681-3515caa1-8754-4936-b0d1-adc494ad27f5.png)

**Expected result:**
The background color for both the buttons are missing and for single row the we can avoid the vertical scrolling.

**Comment by ui-ravishukla** [comment]
@sudhanshu0603 it is final from client end. so we can not change color. and this section is coming from app.

**Comment by sudhanshu0603** [comment]
@ui-ravishukla , is it possible to remove the scrolling of the page.???

**Comment by ui-ravishukla** [comment]
Buttton fixed
