### ISSUE TITLE
Account page after successful login

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Dezymart-Store-ReDesign#37]
**Steps:** 
1:  create account, then click on the address on address page, then the address page will open.

**Actual result:**
1: The address page is not designed well.
https://www.awesomescreenshot.com/video/8098339?key=f6db7b02d31216d7fe7b493a827eaf86
2: The validations are not added on the address page, after filling the input the disabled symbol is coming, the video is attached.

**Expected result:** 
1: The address page have to be designed well.
2: The validation have to be used in the address page

**Comment by ui-ravishukla** [comment]
@sudhanshu0603 we can not change in account page (after login) (theme issue).

**Comment by sudhanshu0603** [comment]
This point need to be discussed for the account details page.

**Comment by ui-ravishukla** [comment]
@sudhanshu0603 After discussing it, keep it in the issue, don't keep it like this.

**Comment by devSuneel** [comment]
resolved

**Comment by sudhanshu0603** [comment]
ok ,resolved
