### ISSUE TITLE
Menu links are not vertically align in header.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Dezymart-Store-ReDesign#4]
**The actual result** 
![image](https://user-images.githubusercontent.com/102131636/159912491-91ad652f-5578-4243-abbf-d999e391acb0.png)

**The expected result:** 
Menu should be vertically aligned in header.

**Comment by sudhanshu0603** [comment]
@ui-ravishukla , when we hover over the navigation menus then white background is coming so the navigation menus have to come in the middle  or we can say have equal space from top and bottom.
The issue link:

**Comment by ui-ravishukla** [comment]
https://www.awesomescreenshot.com/video/8108320?key=1705a6c236aaec68243b6307d69090e4
@sudhanshu0603 I have already told you. please check video.

**Comment by sudhanshu0603** [comment]
This point need to be discussed. @ui-ravishukla
