### ISSUE TITLE
cart page the clear cart button is missing.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Dezymart-Store-ReDesign#40]
**Actual result:** 
When we add any product to the cart then the clear button is not added in the cart page.
![image](https://user-images.githubusercontent.com/102131636/160391378-b01833e9-56ab-4ba9-87d7-238484ce9809.png)

**Expected result:** 
We can add the clear button in the cart page.

**Comment by devSuneel** [comment]
A single button is appearing on all site,this is the advanced functionality of Galleria 3.1 theme if we changed this then other code will hamper so this is not possible

**Comment by sudhanshu0603** [comment]
ok, resolved
