### ISSUE TITLE
browse by category.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Dezymart-Store-ReDesign#41]
**The actual result:** 
The sliders are not used for the this section, 
The issue video: https://www.awesomescreenshot.com/video/8099687?key=1633bb2f52c36ede543f253a8ddb9dd9

**The expected result:** 
We can use the sliders for this section , it will reduce the scrolling of the page. (  homepage)

**Comment by ui-ravishukla** [comment]
@sudhanshu0603 no need for slider here.  because there won't be any more collections added.

**Comment by sudhanshu0603** [comment]
ok,

**Comment by sudhanshu0603** [comment]
This can be discussed what will be much better. @Shweta-PC

**Comment by Shweta-PC** [comment]
Its same as red dress
