### ISSUE TITLE
Accordions are missing in the footer section in mobile view.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Dezymart-Store-ReDesign#44]
**Actual result:**
The accordion are missing in the footer section for mobile view.
![image](https://user-images.githubusercontent.com/102131636/160401895-531d7ff1-f310-473f-834d-1a1889927f9c.png)

**Expected results:**
The accordions have to be used in the footer section for reducing the scrolling of the footer.

**Comment by ui-ravishukla** [comment]
@devSuneel pls check if need then add accordion.

**Comment by devSuneel** [comment]
https://h4jsqn00xqbwturl-56773443766.shopifypreview.com

**Comment by sudhanshu0603** [comment]
ok, resolved
