### ISSUE TITLE
Filter button in collection page the cross symbol is not coming when we are clicking on the filter button.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Dezymart-Store-ReDesign#46]
**Actual result:**
The cross symbol is not coming inside the filter when we click on it in collection page.
![image](https://user-images.githubusercontent.com/102131636/160403599-3c3d601a-5f30-4475-9193-0d5719190156.png)

Expected result: 
The cross symbol have to come inside the filter when we click on it, it will be much better.

**Comment by devSuneel** [comment]
resolved

**Comment by sudhanshu0603** [comment]
ok, resolved
