### ISSUE TITLE
images section above the footer in mobile view,

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Dezymart-Store-ReDesign#47]
**Actual result:** 
The images section above the footer the images are cropping for mobile view.

The issue video: https://www.awesomescreenshot.com/video/8100765?key=bc21635b73c6db6f03e2fa4af1eaf986 
**Respected result:** 
The images have to be aligned properly, they should not be cropped for the mobile view.

----------------------------------------------------------------------------------------------------------------------------------
**RETESTING:**
**Actual result:** 
When we are clicking on all the dots of navigation then it is not clicking sometime.
**The video issue:** 
https://www.awesomescreenshot.com/video/8118557?key=ccd48abdfaebab3aff34f909ef7e30c2

**Expected result:** 
All dots of navigation of this section have to be clickable and opens the page related to it.

**Comment by ui-ravishukla** [comment]
@sudhanshu0603 This is the slider of the theme, so there is an issue with the image, now i have corrected it, it cannot be more correct than this.

**Comment by ui-ravishukla** [comment]
@sudhanshu0603  I have already told you this is theme functionality. we can not change this.

**Comment by sudhanshu0603** [comment]
ok @devSuneel / @ui-ravishukla ,  when we clicking on the 3rd and 4th dots then it is not working on clicking on dots.

**Comment by ui-ravishukla** [comment]
Underlines fixed
