### ISSUE TITLE
Product page

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Dezymart-Store-ReDesign#48]
**The actual result:** 
1: When we click on the thumbnail images then the border is not coming over the images of thumbnail.
**The url :** https://8jul4942fz5ea8w7-56773443766.shopifypreview.com/products/knee-heating-pads-wrap-for-men-and-women-hot-compress-therapy-thermal-pads-for-cramps-and-arthritis-pain-relief
**The issue :** 
![image](https://user-images.githubusercontent.com/102131636/160406007-c85400a9-69e6-480f-8d51-093610ed16f4.png)
2:  The sliders arrows are not visible properly in the thumbnail images.

Expected result: 
1: The border have to come when we click on the thumbnails images.
2: The sliders arrows have to be visible properly  in the product page.
-----------------------------------------------------------------------------------------------------------------------------------
**Retesting:**
**Actual result:**
1: The border have to be visible properly, and slider have to be in a fixed position it is moving up and down when we are  clicking on the thumbnail images.
**The issue video:** 
https://www.awesomescreenshot.com/video/8117913?key=0d0f8057b9894b1f7e7dfb58681f2533
**Expected result:**
1: The sliders arrow have to be visible properly and the border have to be visible properly, and some time when we are clicking on the sliders then slider is moving down and extra spacing is coming.

**Comment by devSuneel** [comment]
https://h4jsqn00xqbwturl-56773443766.shopifypreview.com

**Comment by sudhanshu0603** [comment]
ok , resolved
