### ISSUE TITLE
Learn more button in product page in mobile view

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Dezymart-Store-ReDesign#49]
**The actual result:** 
The issue video : https://www.awesomescreenshot.com/video/8101010?key=2b6df56cb735235e92f527b022df2964
When we open the product page and when we click on the learn more button then the horizontal scrolling is coming and also in product  page the horizontal scrolling is coming.

**The expected :** 
There should not be any horizontal scrolling in the product page.

----------------------------------------------------------------------------------------------------------------------------------------

**RETESTING :** 
**Actual result:** 
1:  The cross symbol is coming over the text when we click on the Learn more link in the product page.
![image](https://user-images.githubusercontent.com/102131636/160582799-b807a1b2-0aa4-4834-ba60-752dba7c8778.png)

2:  When we are clicking on the sliders on thumbnails images then it is moving up and down sometimes and the sliders are not visible properly.
The issue video: https://www.awesomescreenshot.com/video/8117913?key=0d0f8057b9894b1f7e7dfb58681f2533

**Expected result:**
1: The cross symbol must be visible properly.
2: The sliders have to be visible properly and should be in one position and  there should not be extra spacing when we the slider is coming down to the thumbnail images.

**Comment by sudhanshu0603** [comment]
@ui-ravishukla , please review it, some of the issue reflected i have added retesting point above.

**Comment by ui-ravishukla** [comment]
slider issue solved. and popup is coming from app. so no css is being applied,
