### ISSUE TITLE
facebook icon on the footer

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Dezymart-Store-ReDesign#50]
**The actual result:** 
When hove over the facebook icon on footer then the color is not coming as it is coming in facebook icon.
![image](https://user-images.githubusercontent.com/102131636/160595607-73fa18ab-f0e5-4040-ad75-a3b7e17b513f.png)

**The expected result:** 
On hover on social media icon the color have to be same as it is coming for facebook.

**Comment by ui-ravishukla** [comment]
@sudhanshu0603 The color that is coming on hover is coming from the color of the website, we cannot change it.

**Comment by sudhanshu0603** [comment]
ok , @ui-ravishukla
