### ISSUE TITLE
The logo can be aligned in the centre and the hambergur can be aligned to the left it will be much better.(  Suggestion ))

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Dezymart-Store-ReDesign#51]
**The actual result:** 
Th logo is coming to the left .
**The expected result:**
The logo cam be aligned in the centre and the hambergur can be aligned to the left side on header it will be much better. ( Mobile )

**Comment by ui-ravishukla** [comment]
@sudhanshu0603 It is not possible in this because mobile view is being managed from the code of desktop itself.

**Comment by sudhanshu0603** [comment]
ok , @ui-ravishukla .
