### ISSUE TITLE
Accordion in the product page when we click on accordion then previous opened have to be closed

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Dezymart-Store-ReDesign#53]
**Actual result:** 
When we click on the accordions on the product page then the previously opened accordion is not closing.
**The issue video:**
https://www.awesomescreenshot.com/video/8119784?key=c44eef2bfce8d56d79437974bb436286

**Expected result:**  
The previously opened accordion have to be closed when we clicking on another accordion.
--------------------------------------------------------------------------------------------------------------------------------------------
**RETESTING:**
**Actual result:**
When we click on the another accordion then the previously accordion is not closing.
**Expected result:** 
When we are clicking on the another accordion then the previously accordion have to be closed.

**Comment by devSuneel** [comment]
this is theme functionality @sudhanshu0603 no need to change this if we changed this then other things would be hampered

**Comment by sudhanshu0603** [comment]
ok @devSuneel , please review, it is not working.

**Comment by devSuneel** [comment]
resolved

**Comment by devSuneel** [comment]
@sudhanshu0603 it is not an issue, it is coming through the theme we can't change it otherwise theme functionality will hamper

**Comment by Shweta-PC** [comment]
Fixed
