### ISSUE TITLE
Product page you may also like section product images can be can be aligned to left it will be much better.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Dezymart-Store-ReDesign#54]
**Actual result:**
The product images on the you may also like section may space is coming to the left of it.
The issue : 
![image](https://user-images.githubusercontent.com/102131636/160602698-ab970c5a-54c1-4c0a-9914-1874368913e7.png)
The url : https://h4jsqn00xqbwturl-56773443766.shopifypreview.com/products/cutout-split-puff-sleeve-maxi-dress

**Expected result:** 
1: In You may also like section the spacing to its left have to be less it will be much better according to UX.

----------------------------------------------------------------------------------------------------------------------------------------
**RETESTING:** 
**Actual result:**
You may also like section now the producting are attached to the left side of the screen, 

**Expected result:** 
The images of this section have very less space to the left side, it should not be attached to the left side of the screen.

**Comment by ui-ravishukla** [comment]
@sudhanshu0603 In the concept of scroll it will remain like this. this is not issue.

**Comment by sudhanshu0603** [comment]
ok @ui-ravishukla .
