### ISSUE TITLE
product page when we click on the addtocart button then the wishlist button is disappearing.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Dezymart-Store-ReDesign#56]
**Actual result:** 
When we click on the add to cart button then when we click on the cross symbol of cart section then the wishlist button is not coming on the product page.
**The issue:** https://www.awesomescreenshot.com/video/8120656?key=fba8fbcb932f26bd9d20d0ef8d1c8e4d

**Expected result:**
Wishlist button should not be disappears when we click on the addtocart button.

**Comment by sudhanshu0603** [comment]
@devSuneel , what will be the solution for this ???

**Comment by devSuneel** [comment]
https://8ul6go8j4fcgn46w-56773443766.shopifypreview.com

@sudhanshu0603 please check  I fixed it by refreshing the page

**Comment by sudhanshu0603** [comment]
@devSuneel , the page is refreshing. it is not looking good.
