### ISSUE TITLE
page  is refreshing  when we are clicking on the cross symbol inside hambergur

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Dezymart-Store-ReDesign#61]
**Actual result:**
When we are clicking on the cross symbol inside the hambergur then the page is refreshing.
The video issue: https://www.awesomescreenshot.com/video/8159144?key=66e0a7aa2918c29934580eec98858ee0
**Expected result:**
When we click on the cross symbol then the page should not be reloaded, it will be much better.

**Comment by devSuneel** [comment]
resolved

**Comment by sudhanshu0603** [comment]
ok, resolved
