### ISSUE TITLE
collection page

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Dezymart-Store-ReDesign#62]
The url: https://dezymart.com/collections/

**Actual ressult:** 
The image  is not added in collection page.
![image](https://user-images.githubusercontent.com/102131636/161520721-a42efcea-6de7-4784-b99e-0ed432420916.png)
**Expected result:**
The images have to added for the collection page.

**Comment by devSuneel** [comment]
@sudhanshu0603 it is a collection list page and it will display all the collections so some collections don't have a collection image

**Comment by sudhanshu0603** [comment]
ok, resolved
