### ISSUE TITLE
The header navigation passing the hash value.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Dezymart-Store-ReDesign#8]
**The actual result:**
![image](https://user-images.githubusercontent.com/102131636/160070322-8f155976-cc00-4e9b-8394-65e3f058253d.png)
When we click on the header navigation then it is passing the hash value.

**The expected result:**
When we click on the menu in navigation then it should open the page related to it as it is happening when we are clicking on the health  and beauty it is opening the page related to it.

**Comment by devSuneel** [comment]
resolved 

https://b1z09xsd27boxuhp-56773443766.shopifypreview.com

**Comment by sudhanshu0603** [comment]
ok
