### ISSUE TITLE
Brand ambassadors navigation in the header

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Dezymart-Store-ReDesign#9]
**Steps:**
1: Click on the brand ambassadors on the header navigation menu.
2: When we click on the send button then form will submit without filling the data.

**The actual result:**
The video url:  https://www.awesomescreenshot.com/video/8060298?key=419564765d9150b604ccd2e43e26c043 

**The expected result:**
The form validations should be used properly, without filling the input form should not submit.
----------------------------------------------------------------------------------------------------------------------------------------

**RETESTING :**

1: name should not accept the numbers and special characters for name.
**2 Email valid inputs :** 
karan@gmail.com
karan23@gmail.com
**Invalid inputs :** 
424@gmail.com
@gmail.com

The issue video is attached: 
https://www.awesomescreenshot.com/video/8097140?key=68bb4971996434f273a855818a07ac3b

**Comment by devSuneel** [comment]
resolved

https://b1z09xsd27boxuhp-56773443766.shopifypreview.com

**Comment by sudhanshu0603** [comment]
need to discuss the validation points

**Comment by Shweta-PC** [comment]
Resolved
